courses:
    path:     /courses
    defaults: { _controller: App\Controller\CoursesController, tab: courses }

categories:
    path:     /courses/categories
    defaults: { _controller: FrameworkBundle:Redirect:redirect, permanent: true, route: courses }

category:
    path:     /courses/categories/{categorySlug}
    defaults: { _controller: App\Controller\CoursesController, tab: courses }

course:
    path:     /courses/{courseSlug}
    defaults: { _controller: App\Controller\CourseController, tab: courses }

lessons:
    path:     /courses/{courseSlug}/lessons
    defaults: { _controller: FrameworkBundle:Redirect:redirect, permanent: true, route: course }

lesson:
    path:     /courses/{courseSlug}/lessons/{lessonSlug}
    defaults: { _controller: App\Controller\LessonController, tab: courses }

reset:
    path:     /settings/reset
    defaults: { _controller: App\Controller\ResetController }
    methods:  [ POST ]

settings:
    path:     /settings
    defaults: { _controller: App\Controller\SettingsController }

imprint:
    path:     /imprint
    defaults: { _controller: App\Controller\ImprintController }

landing_page:
    path:     /
    defaults: { _controller: App\Controller\LandingPageController, tab: home }

not_found:
    path:     /{anything}
    defaults: { _controller: App\Controller\NotFoundController }
    requirements:
        anything: ".+"
